default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: "Parsazare1378"
  pool: 5

development:
  <<: *default
  database: podcast_directory_development

test:
  <<: *default
  database: podcast_directory_test

production:
  <<: *default
  database: podcast_directory_production
